title: "A-Level Revision"
description: "GitHub Pages site for A-Level (revision) work + notes"
theme: minimal-mistakes-jekyll

url: "https://choppovm.github.io"
baseurl: "/a-level-revision"

plugins:
  - jekyll-include-cache

# Theme skin (color scheme)
minimal_mistakes_skin: "default"

# Use the "main" navigation defined in _data/navigation.yml
navigation: main

# Collections (so pages output properly)
collections:
  pages:
    output: true
